# Generated by Django 5.2.2 on 2025-09-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_photographerprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerprofile',
            name='email',
        ),
    ]
