# Generated by Django 5.2.2 on 2025-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
