# Generated by Django 5.2.2 on 2026-08-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
